name: idea_envalutor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ Added for icon change

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png                # ✅ Logo added in assets

# ✅ App Icon Configuration
flutter_icons:
  android: true

  image_path: "assets/logo.png"       # Path to your logo image
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icon
  adaptive_icon_foreground: "assets/logo.png"
